apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler-sa
  namespace: cloud-db
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscaler-cluster-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-cluster-binding
subjects:
- kind: ServiceAccount
  name: autoscaler-sa
  namespace: cloud-db
roleRef:
  kind: ClusterRole
  name: autoscaler-cluster-role
  apiGroup: rbac.authorization.k8s.io