apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler
  namespace: cloud-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      serviceAccountName: autoscaler-sa
      containers:
      - name: autoscaler
        image: akkaraphont/autoscaler:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"